Testing tests.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -53,14 +53,14 @@ jobs:
           at: /tmp/workspace
 
       - run:
-          name: Configure
+          name: Build Selenium Test Container
+          background: true
           command: |
-            echo '127.0.0.1  test.planet4.dev' | sudo tee --append /etc/hosts
-
-      - run:
-          name: Clone Selenium Tests
-          command: |
-            git clone https://github.com/greenpeace/planet4-selenium-tests
+            git clone https://github.com/greenpeace/planet4-docker-selenium-tests
+            pushd planet4-docker-selenium-tests
+            docker build -t planet4-selenium-tests .
+            popd
+            touch /tmp/workspace/selenium-container-built
 
       - run:
           name: Clone planet4-docker-compose
@@ -75,7 +75,7 @@ jobs:
             export OPENRESTY_IMAGE=gcr.io/planet-4-151612/planet4-base-openresty:${BUILD_TAG}
 
             pushd planet4-docker-compose
-            docker-compose -f docker-compose.stateless.yml up -d
+            docker-compose -p test -f docker-compose.stateless.yml up -d
             popd
 
       - run:
@@ -92,7 +92,7 @@ jobs:
             do
               # Curl to container and expect status code 200
               set +e
-              docker run --network "container:planet4dockercompose_openresty_1" --rm appropriate/curl -s -k "http://localhost:80" | grep -q "greenpeace"
+              docker run --network "container:test_openresty_1" --rm appropriate/curl -s -k "http://localhost" | grep -q "greenpeace"
 
               if [[ $? -eq 0 ]]
               then
@@ -107,7 +107,7 @@ jobs:
               if [[ $loop -lt 1 ]]
               then
                 >&2 echo "[ERROR] Timeout waiting for docker-compose to start"
-                >&2 docker-compose -p build logs
+                >&2 docker-compose -p test logs
                 exit 1
               fi
 
@@ -115,13 +115,56 @@ jobs:
             done
 
       - run:
-          name: Run Selenium Tests
+          name: Configure Selenium container
           command: |
-            pushd planet4-selenium-tests
-            vendor/bin/phpunit -c tests/ --group p4
+            pushd planet4-docker-selenium-tests
+            cat variables.env.example | sed "s/test.planet4.dev/localhost/g" > /tmp/workspace/var/variables.env
             popd
 
+      - run:
+          name: Configure WP Options
+          command: |
+            source /tmp/workspace/var/variables.env
+            docker exec test_php-fpm_1 -- wp option set siteurl "http://localhost"
+            docker exec test_php-fpm_1 -- wp option set home "http://localhost"
+            docker exec test_php-fpm_1 -- wp user create ${PLANET4_USER} noreply@greenpeace.org --role=administrator --user_pass=${PLANET4_USER_PASS}
+            docker exec test_redis_1 redis-cli flushdb
 
+      - run:
+          name: Wait for Selenium container to build
+          command: |
+            # 2 seconds * 150 == 5+ minutes
+            interval=2
+            loop=150
+
+            while [ ! -f /tmp/workspace/selenium-container-built ]
+            do
+              loop=$((loop-1))
+              if [[ $loop -lt 1 ]]
+              then
+                >&2 echo "[ERROR] Timeout waiting for docker-compose to start"
+                >&2 docker-compose logs
+                exit 1
+              fi
+              sleep $interval
+            done
+
+      - run:
+          name: Run Selenium Tests
+          command: |
+            pushd planet4-docker-selenium-tests
+            docker run --rm \
+              --env-file /tmp/workspace/var/variables.env \
+              --name planet4-tests \
+              --network "container:test_openresty_1" \
+              --shm-size=2g \
+              planet4-selenium-tests
+            popd
+
+      - persist_to_workspace:
+          root: /tmp/workspace
+          paths:
+            - var
 
   deploy-develop:
     <<: *defaults
