Selenium tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,129 +41,129 @@ jobs:
             - var
             - src
 
-  # test-selenium:
-  #   <<: *defaults
-  #   steps:
-  #     - setup_remote_docker
-  #
-  #     - attach_workspace:
-  #         at: /tmp/workspace
-  #
-  #     - run:
-  #         name: Build Selenium Test Container
-  #         background: true
-  #         command: |
-  #           git clone https://github.com/greenpeace/planet4-docker-selenium-tests
-  #           if ! docker build -t planet4-selenium-tests planet4-docker-selenium-tests
-  #           then
-  #             TYPE="Selenium Container Build" notify-job-failure.sh
-  #             exit 1
-  #           fi
-  #           touch /tmp/workspace/selenium-container-built
-  #
-  #     - run:
-  #         name: Clone planet4-docker-compose
-  #         command: |
-  #           git clone https://github.com/greenpeace/planet4-docker-compose
-  #
-  #     - run:
-  #         name: Start docker-compose
-  #         command: |
-  #           export BUILD_TAG="build-$(cat /tmp/workspace/var/circle-build-num)"
-  #           export APP_IMAGE=gcr.io/planet-4-151612/planet4-base-app:${BUILD_TAG}
-  #           export OPENRESTY_IMAGE=gcr.io/planet-4-151612/planet4-base-openresty:${BUILD_TAG}
-  #
-  #           pushd planet4-docker-compose
-  #           docker-compose -p test -f docker-compose.stateless.yml up -d
-  #           popd
-  #
-  #     - run:
-  #         name: Wait until containers are ready
-  #         command: |
-  #           # 2 seconds * 150 == 5+ minutes
-  #           interval=2
-  #           loop=150
-  #
-  #           # Number of consecutive successes to qualify as 'up'
-  #           threshold=2
-  #           success=0
-  #           until [[ $success -ge $threshold ]]
-  #           do
-  #             # Curl to container and expect status code 200
-  #             set +e
-  #             docker run --network "container:test_openresty_1" --rm appropriate/curl -s -k "http://localhost" | grep -q "greenpeace"
-  #
-  #             if [[ $? -eq 0 ]]
-  #             then
-  #               success=$((success+1))
-  #               echo "Success: $success/$threshold"
-  #             else
-  #               success=0
-  #             fi
-  #             set -e
-  #
-  #             loop=$((loop-1))
-  #             if [[ $loop -lt 1 ]]
-  #             then
-  #               >&2 echo "[ERROR] Timeout waiting for docker-compose to start"
-  #               >&2 docker-compose -p test logs
-  #               exit 1
-  #             fi
-  #
-  #             [[ $success -ge $threshold ]] || sleep $interval
-  #           done
-  #
-  #     - run:
-  #         name: Configure Selenium container
-  #         command: |
-  #           pushd planet4-docker-selenium-tests
-  #           cat variables.env.example | sed "s/test.planet4.dev/localhost/g" > /tmp/workspace/var/variables.env
-  #           popd
-  #
-  #     - run:
-  #         name: Configure WP Options
-  #         command: |
-  #           source /tmp/workspace/var/variables.env
-  #           docker exec test_php-fpm_1 wp option set siteurl "http://localhost"
-  #           docker exec test_php-fpm_1 wp option set home "http://localhost"
-  #           docker exec test_php-fpm_1 wp user create ${PLANET4_USER} noreply@greenpeace.org --role=administrator --user_pass=${PLANET4_USER_PASS}
-  #           docker exec test_redis_1 redis-cli flushdb
-  #
-  #     - run:
-  #         name: Wait for Selenium container to build
-  #         command: |
-  #           # 2 seconds * 150 == 5+ minutes
-  #           interval=2
-  #           loop=150
-  #
-  #           while [ ! -f /tmp/workspace/selenium-container-built ]
-  #           do
-  #             loop=$((loop-1))
-  #             if [[ $loop -lt 1 ]]
-  #             then
-  #               >&2 echo "[ERROR] Timeout waiting for docker-compose to start"
-  #               >&2 docker-compose logs
-  #               exit 1
-  #             fi
-  #             sleep $interval
-  #           done
-  #
-  #     - run:
-  #         name: Run Selenium Tests
-  #         command: |
-  #           pushd planet4-docker-selenium-tests
-  #           docker run --rm \
-  #             --env-file /tmp/workspace/var/variables.env \
-  #             --name planet4-tests \
-  #             --network "container:test_openresty_1" \
-  #             --shm-size=2g \
-  #             planet4-selenium-tests
-  #           popd
-  #
-  #     - persist_to_workspace:
-  #         root: /tmp/workspace
-  #         paths:
-  #           - var
+  test-selenium:
+    <<: *defaults
+    steps:
+      - setup_remote_docker
+
+      - attach_workspace:
+          at: /tmp/workspace
+
+      - run:
+          name: Build Selenium Test Container
+          background: true
+          command: |
+            git clone https://github.com/greenpeace/planet4-docker-selenium-tests
+            if ! docker build -t planet4-selenium-tests planet4-docker-selenium-tests
+            then
+              TYPE="Selenium Container Build" notify-job-failure.sh
+              exit 1
+            fi
+            touch /tmp/workspace/selenium-container-built
+
+      - run:
+          name: Clone planet4-docker-compose
+          command: |
+            git clone https://github.com/greenpeace/planet4-docker-compose
+
+      - run:
+          name: Start docker-compose
+          command: |
+            export BUILD_TAG="build-$(cat /tmp/workspace/var/circle-build-num)"
+            export APP_IMAGE=gcr.io/planet-4-151612/planet4-base-app:${BUILD_TAG}
+            export OPENRESTY_IMAGE=gcr.io/planet-4-151612/planet4-base-openresty:${BUILD_TAG}
+
+            pushd planet4-docker-compose
+            docker-compose -p test -f docker-compose.stateless.yml up -d
+            popd
+
+      - run:
+          name: Wait until containers are ready
+          command: |
+            # 2 seconds * 150 == 5+ minutes
+            interval=2
+            loop=150
+
+            # Number of consecutive successes to qualify as 'up'
+            threshold=2
+            success=0
+            until [[ $success -ge $threshold ]]
+            do
+              # Curl to container and expect status code 200
+              set +e
+              docker run --network "container:test_openresty_1" --rm appropriate/curl -s -k "http://localhost" | grep -q "greenpeace"
+
+              if [[ $? -eq 0 ]]
+              then
+                success=$((success+1))
+                echo "Success: $success/$threshold"
+              else
+                success=0
+              fi
+              set -e
+
+              loop=$((loop-1))
+              if [[ $loop -lt 1 ]]
+              then
+                >&2 echo "[ERROR] Timeout waiting for docker-compose to start"
+                >&2 docker-compose -p test logs
+                exit 1
+              fi
+
+              [[ $success -ge $threshold ]] || sleep $interval
+            done
+
+      - run:
+          name: Configure Selenium container
+          command: |
+            pushd planet4-docker-selenium-tests
+            cat variables.env.example | sed "s/test.planet4.dev/localhost/g" > /tmp/workspace/var/variables.env
+            popd
+
+      - run:
+          name: Configure WP Options
+          command: |
+            source /tmp/workspace/var/variables.env
+            docker exec test_php-fpm_1 wp option set siteurl "http://localhost"
+            docker exec test_php-fpm_1 wp option set home "http://localhost"
+            docker exec test_php-fpm_1 wp user create ${PLANET4_USER} noreply@greenpeace.org --role=administrator --user_pass=${PLANET4_USER_PASS}
+            docker exec test_redis_1 redis-cli flushdb
+
+      - run:
+          name: Wait for Selenium container to build
+          command: |
+            # 2 seconds * 150 == 5+ minutes
+            interval=2
+            loop=150
+
+            while [ ! -f /tmp/workspace/selenium-container-built ]
+            do
+              loop=$((loop-1))
+              if [[ $loop -lt 1 ]]
+              then
+                >&2 echo "[ERROR] Timeout waiting for docker-compose to start"
+                >&2 docker-compose logs
+                exit 1
+              fi
+              sleep $interval
+            done
+
+      - run:
+          name: Run Selenium Tests
+          command: |
+            pushd planet4-docker-selenium-tests
+            docker run --rm \
+              --env-file /tmp/workspace/var/variables.env \
+              --name planet4-tests \
+              --network "container:test_openresty_1" \
+              --shm-size=2g \
+              planet4-selenium-tests vendor/bin/phpunit -c tests
+            popd
+
+      - persist_to_workspace:
+          root: /tmp/workspace
+          paths:
+            - var
 
   deploy-develop:
     <<: *defaults
@@ -305,6 +305,15 @@ workflows:
     jobs:
     - build-develop:
         context: org-global
+        filters:
+          branches:
+            ignore: master
+          tags:
+            ignore: /.*/
+    - test-selenium:
+        context: org-global
+        requires:
+          - build-develop
         filters:
           branches:
             ignore: master
